## Numeric

In [2]:
n1 <- 15
print(n1)

[1] 15


In [3]:
typeof(n1)

[1] "double"

In [4]:
n2 <- 1.5
print(n2)

[1] 1.5


In [5]:
typeof(n2)

[1] "double"

In [69]:
n3 <- 15L
print(n3)

[1] 15


In [70]:
typeof(n3)

[1] "integer"

## Character

In [6]:
c1 <- 'c'
print(c1)

[1] "c"


In [7]:
typeof(c1)

[1] "character"

In [8]:
c2 <- 'a string of text'
print(c2)

[1] "a string of text"


In [9]:
typeof(c2)

[1] "character"

## Logical

In [10]:
l1 <- TRUE
#l1 <- T
print(l1)

[1] TRUE


In [11]:
typeof(l1)

[1] "logical"

In [12]:
l2 <- FALSE
#l2 <- F
print(l2)

[1] FALSE


In [13]:
typeof(l2)

[1] "logical"

## Vector

In [14]:
v1 <- c(2, 1, 3, 5)
print(v1)

[1] 2 1 3 5


In [15]:
is.vector(v1)

[1] TRUE

In [16]:
v2 <- c('a', 'b', 'c')
print(v2)

[1] "a" "b" "c"


In [17]:
is.vector(v2)

[1] TRUE

In [18]:
v3 <- c(T, T, F, FALSE, TRUE)
print(v3)

[1]  TRUE  TRUE FALSE FALSE  TRUE


In [19]:
is.vector(v3)

[1] TRUE

## Matrix

In [20]:
m1 <- matrix(c(T, T, F, F, T, F), nrow = 2)
print(m1)

     [,1]  [,2]  [,3]
[1,] TRUE FALSE  TRUE
[2,] TRUE FALSE FALSE


In [21]:
is.matrix(m1)

[1] TRUE

In [22]:
m2 <- matrix(c('a', 'b',
               'c', 'd'),
                nrow = 2,
                byrow = T)

print(m2)

     [,1] [,2]
[1,] "a"  "b" 
[2,] "c"  "d" 


In [23]:
m3 <- matrix(c('a', 'b',
               'c', 'd'),
                nrow = 2,
                byrow = F)

print(m3)

     [,1] [,2]
[1,] "a"  "c" 
[2,] "b"  "d" 


## Array

In [24]:
a1 <- array(c(1:24), dim = c(4, 3, 2))
print(a1)

, , 1

     [,1] [,2] [,3]
[1,]    1    5    9
[2,]    2    6   10
[3,]    3    7   11
[4,]    4    8   12

, , 2

     [,1] [,2] [,3]
[1,]   13   17   21
[2,]   14   18   22
[3,]   15   19   23
[4,]   16   20   24



In [25]:
is.array(a1)

[1] TRUE

In [26]:
print(a1[2, 2, 2])

[1] 18


## Data frame

In [27]:
v_numeric <- c(1, 2, 3)
v_character <- c('a', 'b', 'c')
v_logical <- c(T, F, T)
df1 <- as.data.frame(cbind(v_numeric, v_character, v_logical))
df1

v_numeric v_character v_logical
1 1         a           TRUE     
2 2         b           FALSE    
3 3         c           TRUE

## List

In [28]:
o1 <- c(1, 2, 3)
o2 <- c('a', 'b', 'c', 'd')
o3 <- c(T, F, T, T, F)

list1 <- list(o1, o2, o3)
print(list1)

[[1]]
[1] 1 2 3

[[2]]
[1] "a" "b" "c" "d"

[[3]]
[1]  TRUE FALSE  TRUE  TRUE FALSE



In [29]:
list1[[1]][2]

[1] 2

In [30]:
list2 <- list(o1, o2, o3, list1)
print(list2)

[[1]]
[1] 1 2 3

[[2]]
[1] "a" "b" "c" "d"

[[3]]
[1]  TRUE FALSE  TRUE  TRUE FALSE

[[4]]
[[4]][[1]]
[1] 1 2 3

[[4]][[2]]
[1] "a" "b" "c" "d"

[[4]][[3]]
[1]  TRUE FALSE  TRUE  TRUE FALSE




In [31]:
list2[[4]][[2]][3]

[1] "c"

## COERCING TYPES

### Automatic coercion

In [32]:
# Goes to "least restrictive" data type

print(coerce1 <- c(1, 'b', T))
typeof(coerce1)

[1] "1"    "b"    "TRUE"


[1] "character"

In [33]:
# Coerce numeric to integer

print(coerce2 <- 5)
typeof(coerce2)

print(coerce3 <- as.integer(5))
typeof(coerce3)

[1] 5


[1] "double"

[1] 5


[1] "integer"

In [34]:
# Coerce charactar to numeric

print(coerce4 <- c('1', '2', '3'))
typeof(coerce4)

print(coerce5 <- as.numeric(c('1', '2', '3')))
typeof(coerce5)

[1] "1" "2" "3"


[1] "character"

[1] 1 2 3


[1] "double"

In [35]:
# Coerce matrix to data frame

print(coerce6 <- matrix(1:9, nrow = 3))
is.matrix(coerce6)

coerce7 <- as.data.frame(matrix(1:9, nrow = 3, byrow = T))
coerce7
#print(coerce7 <- as.data.frame(coerce6))
is.data.frame(coerce7)

     [,1] [,2] [,3]
[1,]    1    4    7
[2,]    2    5    8
[3,]    3    6    9


[1] TRUE

V1 V2 V3
1 1  2  3 
2 4  5  6 
3 7  8  9

[1] TRUE

In [36]:
coerce7[coerce7$V3 == 9 | coerce7$V3 == 3, ]$V1

[1] 1 7

In [46]:
x <- c(1:3)
y <- rep(c(1:10), each = 3)
df <- as.data.frame(cbind(x, y))
df$x <- factor(df$x, levels = c(1, 2, 3), labels = c('x', 'y', 'z'))
str(df)

'data.frame':	30 obs. of  2 variables:
 $ x: Factor w/ 3 levels "x","y","z": 1 2 3 1 2 3 1 2 3 1 ...
 $ y: int  1 1 1 2 2 2 3 3 3 4 ...


In [68]:
df[order(-df$y), ][c(1:5), ]

x y 
28 x 10
29 y 10
30 z 10
25 x  9
26 y  9